# Generated by Django 2.0.13 on 2019-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Voting category URL slug'),
        ),
    ]
