# Generated by Django 2.0.13 on 2019-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='title_de',
            field=models.CharField(blank=True, max_length=160, verbose_name='Voting title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Voting title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title_fr',
            field=models.CharField(blank=True, max_length=160, verbose_name='Voting title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title_it',
            field=models.CharField(blank=True, max_length=160, verbose_name='Voting title'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title_rm',
            field=models.CharField(blank=True, max_length=160, verbose_name='Voting title'),
        ),
    ]
