# Generated by Django 2.0.13 on 2019-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
