# Generated by Django 2.0.13 on 2019-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190421_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='voting',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Voting URL slug'),
        ),
    ]
