# Generated by Django 2.0.13 on 2019-04-12 22:38

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_voting_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
