# Generated by Django 2.0.13 on 2019-04-30 21:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190429_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='description',
            new_name='description_de',
        ),
        migrations.AddField(
            model_name='voting',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Voting description'),
        ),
        migrations.AddField(
            model_name='voting',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Voting description'),
        ),
        migrations.AddField(
            model_name='voting',
            name='description_it',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Voting description'),
        ),
        migrations.AddField(
            model_name='voting',
            name='description_rm',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Voting description'),
        ),
    ]
