# Generated by Django 2.0.13 on 2019-04-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_voting_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='votes.Voting'),
        ),
        migrations.AddField(
            model_name='voting',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='votes.Voting'),
        ),
    ]
