# Generated by Django 2.0.13 on 2019-05-13 21:20

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20190505_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='admin_brochure',
            new_name='admin_brochure_de',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='video_url',
            new_name='video_url_de',
        ),
        migrations.AddField(
            model_name='voting',
            name='admin_brochure_en',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Formal brochure'),
        ),
        migrations.AddField(
            model_name='voting',
            name='admin_brochure_fr',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Formal brochure'),
        ),
        migrations.AddField(
            model_name='voting',
            name='admin_brochure_it',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Formal brochure'),
        ),
        migrations.AddField(
            model_name='voting',
            name='admin_brochure_rm',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Formal brochure'),
        ),
        migrations.AddField(
            model_name='voting',
            name='video_url_en',
            field=models.URLField(blank=True, verbose_name='Youtube embedded URL'),
        ),
        migrations.AddField(
            model_name='voting',
            name='video_url_fr',
            field=models.URLField(blank=True, verbose_name='Youtube embedded URL'),
        ),
        migrations.AddField(
            model_name='voting',
            name='video_url_it',
            field=models.URLField(blank=True, verbose_name='Youtube embedded URL'),
        ),
        migrations.AddField(
            model_name='voting',
            name='video_url_rm',
            field=models.URLField(blank=True, verbose_name='Youtube embedded URL'),
        ),
    ]
