# Generated by Django 2.0.13 on 2019-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20190421_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured category'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured voting'),
        ),
    ]
