# Generated by Django 2.0.13 on 2019-05-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190513_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='next_voting',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='previous_voting',
        ),
    ]
