# Generated by Django 2.0.13 on 2019-04-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190413_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='next_post',
            new_name='next_voting',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='previous_post',
            new_name='previous_voting',
        ),
    ]
