# Generated by Django 2.0.13 on 2019-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190422_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Voting published'),
        ),
    ]
