# Generated by Django 2.0.13 on 2019-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20190422_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='title',
        ),
        migrations.AddField(
            model_name='voting',
            name='title_de',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='voting',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='voting',
            name='title_fr',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='voting',
            name='title_it',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='voting',
            name='title_rm',
            field=models.CharField(blank=True, max_length=160, verbose_name='title'),
        ),
    ]
