# Generated by Django 2.0.13 on 2019-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_remove_category_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='published',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
