# Generated by Django 2.2.11 on 2020-03-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='admin_brochure',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='Formal brochure'),
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Poll description'),
        ),
        migrations.AddField(
            model_name='poll',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured poll'),
        ),
        migrations.AddField(
            model_name='poll',
            name='thumbnail',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='poll',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Youtube embedded URL'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=100, no_check_for_status=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240, verbose_name='Poll title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('poll_date', models.DateTimeField(verbose_name='Poll final date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Category', verbose_name='Poll category'),
            preserve_default=False,
        ),
    ]
