# Generated by Django 2.2.7 on 2019-11-04 05:35

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Draft', max_length=100, no_check_for_status=True),
        ),
    ]
